version: "3.9"
services:

  queriless_db_server:
    container_name: queriless_db_server
    image: mysql:latest
    restart: unless-stopped
    networks:
      - queriless_net
    ports:
      - "3999:3306"
    environment:
      - MYSQL_DATABASE=student01dev
      - MYSQL_USER=queriless
      - MYSQL_PASSWORD=queriless
      - MYSQL_ROOT_PASSWORD=P@ssw0rd

  queriless_db_admin:
    container_name: queriless_db_admin
    image: adminer
    restart: always
    links:
      - "queriless_db_server:queriless_db_server"
    depends_on:
      - "queriless_db_server"
    networks:
      - queriless_net
    ports:
      - "1999:8080"

  queriless_app:
    container_name: queriless_app
    image: joeydekort/docker-queriless
    restart: always
    links:
      - "queriless_db_server:queriless_db_server"
    depends_on:
      - "queriless_db_server"
    networks:
      - queriless_net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://queriless_db_server:3306/student01dev?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd
    ports:
      - "7777:8080"

networks:
  queriless_net:
